### PR TITLE
If platformID indicates MAME, use mamedb.com to grab actual game name

### PR DESCRIPTION
**Pull request by markusn**
Usually MAME roms do not have a very descriptive filename. Use mamedb to get the actual game title.

### CODE REVIEW

**Comment by streeto** [comment]
I need this feature, so I am trying to merge this locally, but there are line ending issues. When I checkout this commit, the line ending of scraper.py changes to CRLF and ruins the merge. All the other commits are fine (unix LF). Not sure how to fix this.

**Comment by markusn** [comment]
@streeto Seems like ES-scraper used to have CLRF as line ending but changed it at some point. I've updated the pullrequest to reflect the change. Hope it works better now!

**Comment by streeto** [comment]
There's an error (typo?) in the commit, you check `platform` before assigning it.

``` python
        if platform == "Arcade": title = getRealArcadeTitle(title)
        platform = getPlatformName(platformID)
```

No big deal. Other than that, I tested it and it works nicely. Thanks! :-)

**Comment by markusn** [comment]
@streeto doh, I messed up when fixing the CLRF vs. LF thingie. Will you fix and commit the ordering change?

**Comment by streeto** [comment]
It's your feature, it would not be polite for me to fix a simple typo. :-) Please proceed with the fix.

**Pull request merged**
